# Generated by Django 2.0.5 on 2018-05-04 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180504_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 18, 28, 46, 207587, tzinfo=utc)),
        ),
    ]
