# Generated by Django 2.0.5 on 2018-05-04 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180504_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 4, 18, 32, 33, 198260, tzinfo=utc)),
        ),
    ]
